pipeline:
  identifier: Build_LongHe1996_node_js_playwright_browserstack_1739518086366
  name: Build node-js-playwright-browserstack
  orgIdentifier: default
  projectIdentifier: TestHarnessIntegration
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1739518057514
        repoName: LongHe1996/node-js-playwright-browserstack
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
