pipeline:
  identifier: Build_LongHe1996_node_js_playwright_browserstack_1739518086366
  name: Build node-js-playwright-browserstack
  orgIdentifier: default
  projectIdentifier: TestHarnessIntegration
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1739518057514
        repoName: LongHe1996/node-js-playwright-browserstack
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Browserstack
                  identifier: Browserstack
                  spec:
                    shell: Sh
                    command: npx browserstack-node-sdk playwright test --config=./playwright.config.js
                    envVariables:
                      BROWSERSTACK_ACCESS_KEY: yBQSDVqqLvXqbEsoquBU
                      BROWSERSTACK_USERNAME: shiyinshen_c3wtBn
                    imagePullPolicy: Always
                  timeout: 10m
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
